Repository ca-cwds/API, pull requests merged in 2018-06, with the labels that each got.

#464 Version Update
  build.gradle
Labels: Gradle Update

#465 Fixed the bug for Ethnicity Transformer.
  src/main/java/gov/ca/cwds/inject/DataAccessModule.java
  src/main/java/gov/ca/cwds/inject/ServicesModule.java
  src/main/java/gov/ca/cwds/rest/api/domain/Screening.java
  src/main/java/gov/ca/cwds/rest/services/CachingIntakeCodeService.java
  src/main/java/gov/ca/cwds/rest/services/cms/ClientAddressService.java
  src/main/java/gov/ca/cwds/rest/services/submit/CrossReportsTransformer.java
  src/main/java/gov/ca/cwds/rest/services/submit/RaceAndEthnicityTransformer.java
  src/test/java/gov/ca/cwds/data/cms/TestSystemCodeCache.java
  src/test/java/gov/ca/cwds/rest/services/submit/RaceAndEthnicityTransformerTest.java
Labels: Bug Fix

#441 Update entrypoint.sh to use with external parameters parser
  entrypoint.sh
Labels: Enhancement

#478 Update build.gradle
  build.gradle
Labels: patch

#480 Update Jenkinsfile
  Jenkinsfile
Labels: minor

#481 Test tag doe 3318
  Jenkinsfile
Labels: patch

#485 updated jenkins
  Jenkinsfile
Labels: minor

#487 updated jenkins
  Jenkinsfile
Labels: patch

#491 updated changes
  Jenkinsfile
Labels: patch

#492 updated tag
  Jenkinsfile
Labels: patch

#494 updated tag
  Jenkinsfile
Labels: patch

#505 SonarQube Fix
  src/main/java/gov/ca/cwds/data/ns/IntakeLovDao.java
  src/main/java/gov/ca/cwds/data/persistence/cms/EducationProvider.java
  src/main/java/gov/ca/cwds/data/persistence/cms/EducationProviderContact.java
  src/main/java/gov/ca/cwds/data/persistence/cms/OtherAdultInPlacemtHome.java
Labels: SonarQube Fix

#509 Gradle Version Update
  build.gradle
Labels: Gradle Update

#513 Fix for the 500 error on the client SCP
  src/main/java/gov/ca/cwds/data/persistence/cms/Client.java
  src/main/java/gov/ca/cwds/data/persistence/cms/ClientScpEthnicity.java
Labels: Bug Fix

#518 HOT-2056 Adarsh Save Safety Alerts To Legacy
  src/main/java/gov/ca/cwds/data/HibernateStatisticsConsumerRegistry.java
  src/main/java/gov/ca/cwds/fixture/investigation/SafetyAlertsEntityBuilder.java
  src/main/java/gov/ca/cwds/inject/DataAccessModule.java
  src/main/java/gov/ca/cwds/inject/ServicesModule.java
  src/main/java/gov/ca/cwds/rest/api/domain/PostedScreeningToReferral.java
  src/main/java/gov/ca/cwds/rest/api/domain/ScreeningToReferral.java
  src/main/java/gov/ca/cwds/rest/api/domain/SystemCodeCategoryId.java
  src/main/java/gov/ca/cwds/rest/api/domain/investigation/SafetyAlerts.java
  src/main/java/gov/ca/cwds/rest/services/ReferralSatefyAlertsService.java
  src/main/java/gov/ca/cwds/rest/services/ScreeningToReferralService.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/ClientTransformer.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/IntakeAddressConverter.java
  src/main/java/gov/ca/cwds/rest/services/submit/ScreeningTransformer.java
  src/test/java/gov/ca/cwds/data/cms/TestIntakeCodeCache.java
  src/test/java/gov/ca/cwds/data/cms/TestSystemCodeCache.java
  src/test/java/gov/ca/cwds/fixture/MockedScreeningToReferralServiceBuilder.java
  src/test/java/gov/ca/cwds/fixture/ScreeningToReferralResourceBuilder.java
  src/test/java/gov/ca/cwds/rest/api/domain/ScreeningToReferralTest.java
  src/test/java/gov/ca/cwds/rest/api/domain/investigation/SafetyAlertsTest.java
  src/test/java/gov/ca/cwds/rest/business/rules/R00797SensitiveReferralAssignmentTest.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/LastUpdatedTimeIsUniqueTest.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R00796ScreeningToReferralDeleteTest.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R04537FirstResponseDeterminedByStaffPersonIdTest.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R05559SetPrimaryContactStaffPersonIdTest.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R05914DoNotUpdateApprovalStatusTypeTest.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R07577CreateDummyDocsForReferralTest.java
  src/test/java/gov/ca/cwds/rest/services/ReferralSatefyAlertsServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/ScreeningToReferralServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/investigation/SafetyAlertsServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/ScreeningTransformerTest.java
  src/test/resources/fixtures/domain/ScreeningToReferral/validWithWorkerSafety.json
Labels: Enhancement

#533 Refactored Intake Code Converter for Race
  src/main/java/gov/ca/cwds/rest/api/domain/IntakeCodeCache.java
  src/main/java/gov/ca/cwds/rest/api/domain/investigation/contact/PostedContactIntake.java
  src/main/java/gov/ca/cwds/rest/services/CachingIntakeCodeService.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/IntakeCodeConverter.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/IntakeEthnicity.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/IntakeRace.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/IntakeRaceAndEthnicity.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/IntakeRaceAndEthnicityConverter.java
  src/main/java/gov/ca/cwds/rest/services/submit/IntakeCodeConveter.java
  src/main/java/gov/ca/cwds/rest/services/submit/RaceAndEthnicityTransformer.java
  src/main/java/gov/ca/cwds/rest/services/submit/ScreeningTransformer.java
  src/test/java/gov/ca/cwds/data/cms/TestIntakeCodeCache.java
  src/test/java/gov/ca/cwds/rest/services/CachingIntakeCodeServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/screeningparticipant/IntakeCodeConverterTest.java
  src/test/java/gov/ca/cwds/rest/services/screeningparticipant/LegacyDaoMapperEnumTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/IntakeCodeConveterTest.java
Labels: Refactor

#534 Added a check that Screening should be open for saving the participant.
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/ParticipantDaoFactoryImpl.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/ScreeningParticipantService.java
  src/test/java/gov/ca/cwds/rest/services/screeningparticipant/ScreeningParticipantServiceTest.java
Labels: Validation

#538 Adarsh refactor
  src/main/java/gov/ca/cwds/rest/business/reminders/R04464CrossReportLawEnforcementDue.java
  src/main/java/gov/ca/cwds/rest/business/reminders/R04631ReferralInvestigationContactDue.java
  src/main/java/gov/ca/cwds/rest/business/reminders/R05443AndR03341StateIdMissing.java
  src/main/java/gov/ca/cwds/rest/services/ClientParticipants.java
  src/main/java/gov/ca/cwds/rest/services/ParticipantService.java
  src/main/java/gov/ca/cwds/rest/services/ScreeningToReferralService.java
  src/main/java/gov/ca/cwds/rest/services/submit/ParticipantsTransformer.java
  src/test/java/gov/ca/cwds/fixture/ParticipantResourceBuilder.java
  src/test/java/gov/ca/cwds/fixture/ScreeningToReferralResourceBuilder.java
  src/test/java/gov/ca/cwds/rest/api/domain/ParticipantTest.java
  src/test/java/gov/ca/cwds/rest/api/domain/ScreeningToReferralTest.java
  src/test/java/gov/ca/cwds/rest/services/ClientParticipantsTest.java
  src/test/java/gov/ca/cwds/rest/services/ParticipantServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/ScreeningToReferralServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/ParticipantsTransformerTest.java
  src/test/resources/fixtures/domain/ScreeningToReferral/valid/validstr.json
  src/test/resources/fixtures/domain/ScreeningToReferral/validWithSafetyAlert.json
  src/test/resources/fixtures/domain/participant/valid/valid.json
Labels: Refactor

#539 Small fix to the SSN update on participant end point.
  src/main/java/gov/ca/cwds/rest/api/domain/ParticipantIntakeApi.java
Labels: Bug Fix

#546 Fix for the participant end point to handle only zip number.
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/CollateralIndividualTranformer.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/EducationProviderContactTransformer.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/IntakeAddressConverter.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/OtherAdultInPlacemtHomeTransformer.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/OtherChildInPlacemtHomeTransformer.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/ReporterTransformer.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/ServiceProviderTransformer.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/SubstituteCareProviderTransformer.java
  src/test/java/gov/ca/cwds/rest/services/screeningparticipant/CollateralIndividualTranformerTest.java
  src/test/java/gov/ca/cwds/rest/services/screeningparticipant/EducationProviderContactTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/screeningparticipant/OtherAdultInPlacemtHomeTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/screeningparticipant/OtherChildInPlacemtHomeTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/screeningparticipant/ReporterTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/screeningparticipant/ServiceProviderTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/screeningparticipant/SubstituteCareProviderTransformerTest.java
Labels: Refactor

#549 Bug Fix
  src/main/java/gov/ca/cwds/rest/api/domain/cms/Address.java
  src/main/java/gov/ca/cwds/rest/api/domain/cms/Referral.java
  src/main/java/gov/ca/cwds/rest/services/cms/ClientScpEthnicityService.java
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/IntakeCodeConverter.java
  src/test/java/gov/ca/cwds/rest/services/screeningparticipant/IntakeCodeConverterTest.java
Labels: Bug Fix

#554 Fix for the for Race and Ethnicity.
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/IntakeCodeConverter.java
Labels: Bug Fix

#555 gradle version update
  build.gradle
Labels: Gradle Update

#556 Safey Alerts are added to Screener Alert Text
  src/main/java/gov/ca/cwds/rest/resources/ScreeningRelationshipResource.java
  src/main/java/gov/ca/cwds/rest/services/CachingIntakeCodeService.java
  src/main/java/gov/ca/cwds/rest/services/ReferralSafetyAlertsService.java
  src/main/java/gov/ca/cwds/rest/services/ScreeningToReferralService.java
  src/main/java/gov/ca/cwds/rest/services/submit/SafetyAlertsInformation.java
  src/main/java/gov/ca/cwds/rest/services/submit/ScreeningTransformer.java
  src/test/java/gov/ca/cwds/fixture/MockedScreeningToReferralServiceBuilder.java
  src/test/java/gov/ca/cwds/rest/business/rules/R00797SensitiveReferralAssignmentTest.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/LastUpdatedTimeIsUniqueTest.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R00796ScreeningToReferralDeleteTest.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R04537FirstResponseDeterminedByStaffPersonIdTest.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R05559SetPrimaryContactStaffPersonIdTest.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R05914DoNotUpdateApprovalStatusTypeTest.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R07577CreateDummyDocsForReferralTest.java
  src/test/java/gov/ca/cwds/rest/services/ReferralSafetyAlertsServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/ScreeningToReferralServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/ScreeningTransformerTest.java
Labels: Refactor

#558 Participant POST will authorize the clients based on the privilege
  src/main/java/gov/ca/cwds/rest/services/screeningparticipant/ClientTransformer.java
  src/test/java/gov/ca/cwds/rest/services/screeningparticipant/ClientTransformerTest.java
Labels: Enhancement
