Repository ca-cwds/API, pull requests merged in 2018-05, with the labels that each got.

#379 Added a Validation check based on age number
  src/main/java/gov/ca/cwds/data/persistence/ns/ScreeningEntity.java
  src/main/java/gov/ca/cwds/rest/business/rules/R00786VictimAgeRestriction.java
  src/main/java/gov/ca/cwds/rest/services/cms/AllegationPerpetratorHistoryService.java
  src/main/java/gov/ca/cwds/rest/services/cms/ChildClientService.java
  src/main/java/gov/ca/cwds/rest/services/cms/ClientCollateralService.java
  src/main/java/gov/ca/cwds/rest/services/cms/CrossReportService.java
  src/main/java/gov/ca/cwds/rest/services/cms/GovernmentOrganizationCrossReportService.java
  src/main/java/gov/ca/cwds/rest/services/cms/ReporterService.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R00786VictimAgeRestrictionTest.java
Labels: Business Rule

#382 Reverted everything back as ChildClient Story has modified.
  src/main/java/gov/ca/cwds/rest/api/domain/cms/Client.java
  src/main/java/gov/ca/cwds/rest/services/ParticipantService.java
  src/test/java/gov/ca/cwds/rest/api/domain/cms/ClientTest.java
  src/test/java/gov/ca/cwds/rest/services/ParticipantServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/ScreeningToReferralServiceTest.java
Labels: CleanUp

#386 Adarsh validation for dob and age number
  src/main/java/gov/ca/cwds/rest/api/domain/ScreeningToReferral.java
  src/main/java/gov/ca/cwds/rest/business/rules/R00786VictimAgeRestriction.java
  src/main/java/gov/ca/cwds/rest/util/ParticipantUtils.java
  src/main/java/gov/ca/cwds/rest/validation/ValidVictimBirth.java
  src/main/java/gov/ca/cwds/rest/validation/VictimBirthValidator.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R00786VictimAgeRestrictionTest.java
  src/test/java/gov/ca/cwds/rest/validation/VictimBirthValidatorTest.java
Labels: Validation

#392 Gradle Version Update
  build.gradle
Labels: Gradle Update

#391 Adarsh validation for dob and age number
  src/main/java/gov/ca/cwds/rest/validation/VictimBirthValidator.java
  src/test/java/gov/ca/cwds/rest/validation/VictimBirthValidatorTest.java
Labels: CleanUp

#393 Updating the Participant SSN.
  src/main/java/gov/ca/cwds/rest/api/domain/cms/Client.java
  src/main/java/gov/ca/cwds/rest/services/ParticipantService.java
  src/test/java/gov/ca/cwds/rest/api/domain/cms/ClientTest.java
  src/test/java/gov/ca/cwds/rest/services/ParticipantServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/ScreeningToReferralServiceTest.java
Labels: Refactor

#396 Adarsh validation for dob and age number
  src/main/java/gov/ca/cwds/rest/api/domain/Participant.java
  src/main/java/gov/ca/cwds/rest/services/ParticipantService.java
  src/main/java/gov/ca/cwds/rest/validation/VictimBirthValidator.java
Labels: Refactor

#400 HOT-1669 Adarsh R00834 age unit restriction
  src/main/java/gov/ca/cwds/data/persistence/xa/WorkDB2UserInfo.java
  src/main/java/gov/ca/cwds/data/persistence/xa/XAUnitOfWorkAspect.java
  src/main/java/gov/ca/cwds/rest/api/domain/cms/Address.java
  src/main/java/gov/ca/cwds/rest/api/domain/cms/ReferralClient.java
  src/main/java/gov/ca/cwds/rest/business/reminders/R04464CrossReportLawEnforcementDue.java
  src/main/java/gov/ca/cwds/rest/business/rules/CalendarEnum.java
  src/main/java/gov/ca/cwds/rest/business/rules/R00786VictimAgeRestriction.java
  src/main/java/gov/ca/cwds/rest/business/rules/R00834AgeUnitRestriction.java
  src/main/java/gov/ca/cwds/rest/filters/RequestExecutionContextRegistry.java
  src/main/java/gov/ca/cwds/rest/services/ParticipantService.java
  src/test/java/gov/ca/cwds/fixture/CrossReportEntityBuilder.java
  src/test/java/gov/ca/cwds/fixture/ReporterEntityBuilder.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R00834AgeUnitRestrictionTest.java
  src/test/java/gov/ca/cwds/rest/services/ParticipantServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/cms/ClientServiceTest.java
Labels: Business Rule

#410 Changed from creation Date to started date.
  src/main/java/gov/ca/cwds/rest/business/rules/R00834AgeUnitRestriction.java
  src/main/java/gov/ca/cwds/rest/services/ParticipantService.java
  src/test/java/gov/ca/cwds/rest/business/rules/doctool/R00834AgeUnitRestrictionTest.java
Labels: Bug Fix

#419 Added Legacy systemCode id to constructor and entity builder for IntakeLov
  src/main/java/gov/ca/cwds/data/persistence/ns/IntakeLov.java
  src/test/java/gov/ca/cwds/fixture/IntakeLovEntityBuilder.java
Labels: Refactor

#422 Hot 1689 implement in ferb api the screening endpoint submit to absorb intake api
  src/main/java/gov/ca/cwds/inject/ResourcesModule.java
  src/main/java/gov/ca/cwds/inject/ScreeningSubmitServiceBackedResource.java
  src/main/java/gov/ca/cwds/inject/ServicesModule.java
  src/main/java/gov/ca/cwds/rest/api/domain/ParticipantIntakeApi.java
  src/main/java/gov/ca/cwds/rest/api/domain/RaceAndEthnicity.java
  src/main/java/gov/ca/cwds/rest/resources/submit/ScreeningSubmitResource.java
  src/main/java/gov/ca/cwds/rest/services/StaffPersonService.java
  src/main/java/gov/ca/cwds/rest/services/submit/AddressTransformer.java
  src/main/java/gov/ca/cwds/rest/services/submit/AllegationsTransformer.java
  src/main/java/gov/ca/cwds/rest/services/submit/CrossReportsTransformer.java
  src/main/java/gov/ca/cwds/rest/services/submit/ParticipantsTransformer.java
  src/main/java/gov/ca/cwds/rest/services/submit/RaceAndEthnicityTransformer.java
  src/main/java/gov/ca/cwds/rest/services/submit/ScreeningSubmitService.java
  src/main/java/gov/ca/cwds/rest/services/submit/ScreeningTransformer.java
  src/test/java/gov/ca/cwds/data/cms/TestSystemCodeCache.java
  src/test/java/gov/ca/cwds/fixture/ParticipantIntakeApiResourceBuilder.java
  src/test/java/gov/ca/cwds/rest/resources/submit/ScreeningSubmitResourceTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/AddressTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/AllegationsTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/CrossReportsTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/ParticipantsTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/RaceAndEthnicityTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/ScreeningSubmitServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/ScreeningTransformerTest.java
Labels: Enhancement

#427 Gradle Version Update 7.2
  build.gradle
Labels: Gradle Update

#440 Adarsh hot 1973 build intake code cache
  src/main/java/gov/ca/cwds/inject/ServicesModule.java
  src/main/java/gov/ca/cwds/rest/ApiApplication.java
  src/main/java/gov/ca/cwds/rest/api/domain/IntakeCodeCache.java
  src/main/java/gov/ca/cwds/rest/services/CachingIntakeCodeService.java
  src/main/java/gov/ca/cwds/rest/services/IntakeLovService.java
  src/test/java/gov/ca/cwds/data/cms/TestIntakeCodeCache.java
  src/test/java/gov/ca/cwds/inject/ServicesModuleTest.java
  src/test/java/gov/ca/cwds/rest/services/CachingIntakeCodeServiceTest.java
Labels: Enhancement

#446 Adarsh hot 1973 build intake code cache
  src/main/java/gov/ca/cwds/data/ns/IntakeLovDao.java
  src/main/java/gov/ca/cwds/data/persistence/ns/IntakeLov.java
  src/main/java/gov/ca/cwds/inject/ServicesModule.java
  src/main/java/gov/ca/cwds/rest/services/CachingIntakeCodeService.java
  src/main/java/gov/ca/cwds/rest/services/IntakeLovService.java
  src/main/java/gov/ca/cwds/rest/services/cms/StaffPersonIdRetriever.java
  src/test/java/gov/ca/cwds/data/ns/IntakeLovDaoTest.java
  src/test/java/gov/ca/cwds/rest/services/CachingIntakeCodeServiceTest.java
Labels: Refactor

#450 gradle update for System Code "0" check
  build.gradle
  src/main/java/gov/ca/cwds/rest/services/hoi/HOICaseService.java
Labels: Bug Fix

#453 As per the discussion changed it to List.
  src/main/java/gov/ca/cwds/data/ns/IntakeLovDao.java
  src/main/java/gov/ca/cwds/rest/api/domain/IntakeCodeCache.java
  src/main/java/gov/ca/cwds/rest/services/CachingIntakeCodeService.java
  src/main/java/gov/ca/cwds/rest/services/IntakeLovService.java
  src/test/java/gov/ca/cwds/data/cms/TestIntakeCodeCache.java
  src/test/java/gov/ca/cwds/data/ns/IntakeLovDaoTest.java
  src/test/java/gov/ca/cwds/rest/services/CachingIntakeCodeServiceTest.java
Labels: Refactor

#458 Hot 1689 implement in ferb api the screening endpoint submit to absorb intake api
  build.gradle
  src/main/java/gov/ca/cwds/rest/api/domain/IntakeCodeCache.java
  src/main/java/gov/ca/cwds/rest/business/rules/CalendarEnum.java
  src/main/java/gov/ca/cwds/rest/services/CachingIntakeCodeService.java
  src/main/java/gov/ca/cwds/rest/services/submit/AddressTransformer.java
  src/main/java/gov/ca/cwds/rest/services/submit/AllegationsTransformer.java
  src/main/java/gov/ca/cwds/rest/services/submit/CrossReportsTransformer.java
  src/main/java/gov/ca/cwds/rest/services/submit/IntakeCodeConveter.java
  src/main/java/gov/ca/cwds/rest/services/submit/ParticipantsTransformer.java
  src/main/java/gov/ca/cwds/rest/services/submit/RaceAndEthnicityTransformer.java
  src/main/java/gov/ca/cwds/rest/services/submit/ScreeningSubmitService.java
  src/main/java/gov/ca/cwds/rest/services/submit/ScreeningTransformer.java
  src/test/java/gov/ca/cwds/data/cms/TestIntakeCodeCache.java
  src/test/java/gov/ca/cwds/data/cms/TestSystemCodeCache.java
  src/test/java/gov/ca/cwds/fixture/ParticipantIntakeApiResourceBuilder.java
  src/test/java/gov/ca/cwds/rest/business/rules/CalendarEnumTest.java
  src/test/java/gov/ca/cwds/rest/services/CachingIntakeCodeServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/AddressTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/AllegationsTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/CrossReportsTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/GenderTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/IntakeCodeConveterTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/ParticipantsTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/RaceAndEthnicityTransformerTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/ScreeningSubmitServiceTest.java
  src/test/java/gov/ca/cwds/rest/services/submit/ScreeningTransformerTest.java
Labels: Refactor
